force-app/main/default/objects/Group_Result__c/Group_Result__c.object-meta.xml
<CustomObject>
    <label>Group Result</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Group Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Result__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GroupResultAPI.cls
@RestResource(urlMapping='/groupResults/*')
global with sharing class GroupResultAPI {
    
    @HttpGet
    global static List<Group_Result__c> getGroupResults() {
        RestRequest req = RestContext.request;
        String tournamentId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        return [SELECT Id, Name FROM Group_Result__c WHERE Tournament__c = :tournamentId];
    }
}