force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date and time of the tournament.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date and time of the tournament.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the tournament is ongoing, completed, or upcoming.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Upcoming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TournamentFactory.cls
public with sharing class TournamentFactory implements RecordFactory {
    
    public List<Tournament__c> createRecord(List<Map<String, Object>> recordData) {
        List<Tournament__c> tournaments = new List<Tournament__c>();
        for(Map<String, Object> record : recordData) {
            Tournament__c tournament = new Tournament__c(
                Name=(String) record.get('Name'),
                Start_Date__c=(Date) record.get('Start_Date__c'),
                End_Date__c=(Date) record.get('End_Date__c'),
                Status__c=(String) record.get('Status__c'),
                Approved__c=true
            );
            tournaments.add(tournament);
        }
        if(tournaments.size() > 0 && Schema.sObjectType.Tournament__c.isCreateable()) {
            insert tournaments;
        }
        return tournaments;
    }
}