force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>Represents a group within the tournament&apos;s group stage.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <description>Reference to the tournament this group belongs to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Group_Result__c/Group_Result__c.object-meta.xml
<CustomObject>
    <label>Group Result</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Group Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Result__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Result__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Result__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Represents a participating team in the tournament.</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country the team represents.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date and time of the tournament.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date and time of the tournament.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tournament__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates whether the tournament is ongoing, completed, or upcoming.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Upcoming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tournament Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Standings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TournamentTriggerHelper_Test.cls
@isTest
private class TournamentTriggerHelper_Test {
    
    @TestSetup
    static void setupTestData() {
        // Create test data for Tournament
        Tournament__c testTournament = new Tournament__c(
            Name='Test Tournament',
            Status__c='Completed',
            Start_Date__c= (Date) Date.today().addDays(-30),
            End_Date__c= (Date) Date.today().addDays(-1),
            Approved__c=True
        );
        insert testTournament;

        // Create test data for Group
        Group__c testGroup = new Group__c(
            Tournament__c=testTournament.Id,
            Name='Group T',
            Approved__c=True
        );
        insert testGroup;

        // Create test data for Team
        Team__c testTeam = new Team__c(
            Name='Morocco',
            Country__c='Morocco'
        );
        insert testTeam;

        // Create test data for Tournament_Team__c
        Tournament_Team__c testTournamentTeam = new Tournament_Team__c(
            Group__c = testGroup.Id,
            Tournament__c = testTournament.Id,
            Team__c = testTeam.Id
        );
        insert testTournamentTeam;
    }

    @isTest
    static void testBeforeInsert() {
        Test.startTest();
        Id tournamentId = [SELECT Id FROM Tournament__c LIMIT 1][0].Id;
        Id groupId = [SELECT Id FROM Group__c LIMIT 1][0].Id;
        Id teamId = [SELECT Id FROM Team__c LIMIT 1][0].Id;
        // Query for Group_Result__c records
        List<Group_Result__c> groupResults = [SELECT Id, Group__c, Tournament__c, Team__c, Approved__c FROM Group_Result__c];
        // Assert that Group_Result__c records were created
        System.assertEquals(1, groupResults.size(), 'We should have only one group result');
        Group_Result__c groupResult = groupResults[0];
        System.assertEquals(groupId, groupResult.Group__c, 'We should have the same Group');
        System.assertEquals(tournamentId, groupResult.Tournament__c, 'We should have the same tournament');
        System.assertEquals(teamId, groupResult.Team__c, 'We should have the same Team');
        System.assertEquals(true, groupResult.Approved__c, 'Group Result should be approved');
        Test.stopTest();
    }
}