force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>Represents a group within the tournament&apos;s group stage.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <description>Reference to the tournament this group belongs to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Group_Result__c/Group_Result__c.object-meta.xml
<CustomObject>
    <label>Group Result</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Group Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Result__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group_Result__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Result__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Group Results</relationshipLabel>
    <relationshipName>Group_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Represents a participating team in the tournament.</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/Tournament_Team__c.object-meta.xml
<CustomObject>
    <label>Tournament Team</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tournament Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournament Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament_Team__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tournament_Team__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Tournament Teams</relationshipLabel>
    <relationshipName>Tournament_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TournamentTriggerHelper.cls
public with sharing class TournamentTriggerHelper extends TriggerHandler {
    
    public TournamentTriggerHelper() {
        this.setMaxLoopCount(1);
    }

    public override void beforeInsert() {
        List<Tournament_Team__c> tournamentTeams = (List<Tournament_Team__c>) Trigger.new;
        List<Group_Result__c> groupResults = new List<Group_Result__c>();
        for (Tournament_Team__c team : tournamentTeams) {
            Group_Result__c groupResult = new Group_Result__c(
                Group__c=team.Group__c,
                Tournament__c=team.Tournament__c,
                Team__c=team.Team__c,
                Approved__c=true
            );
            groupResults.add(groupResult);
        }

        if(groupResults.size() > 0) {
            insert groupResults;
        }
    }
}