force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <description>Represents a group within the tournament&apos;s group stage.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <description>Reference to the tournament this group belongs to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the group in which the match is played (for group stage matches).</description>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Match_Date__c.field-meta.xml
<CustomField>
    <fullName>Match_Date__c</fullName>
    <description>Date and time of the match.</description>
    <label>Match Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Indicates the stage of the tournament (e.g., Group Stage, Round of 16, Quarter-finals, etc.).</description>
    <label>Round</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rounds</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_1__c.field-meta.xml
<CustomField>
    <fullName>Team_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team 1</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_1_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_1_Score__c</fullName>
    <label>Team 1 Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_2__c.field-meta.xml
<CustomField>
    <fullName>Team_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team 2</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Team 2)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_2_Score__c.field-meta.xml
<CustomField>
    <fullName>Team_2_Score__c</fullName>
    <label>Team 2 Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <description>Reference to the tournament the match belongs to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchFactory.cls
public with sharing class MatchFactory implements RecordFactory {
    
    public List<Match__c> createRecord(List<Map<String, Object>> recordData) {
        List<Match__c> matches = new List<Match__c>();
        for(Map<String, Object> record : recordData) {
            Match__c match = new Match__c(
                Tournament__c=(Id) record.get('Tournament__c'),
                Match_Date__c=(Datetime) record.get('Match_Date__c'),
                Group__c=(Id) record.get('Group__c'),
                Round__c=(String) record.get('Round__c'),
                Team_1__c=(Id) record.get('Team_1__c'),
                Team_2__c=(Id) record.get('Team_2__c'),
                Team_1_Score__c=(Integer) record.get('Team_1_Score__c'),
                Team_2_Score__c=(Integer) record.get('Team_2_Score__c'),
                Approved__c=true
            );
            matches.add(match);
        }
        if(matches.size() > 0) {
            insert matches;
        }
        return matches;
    }
}