force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Match_Date__c.field-meta.xml
<CustomField>
    <fullName>Match_Date__c</fullName>
    <description>Date and time of the match.</description>
    <label>Match Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_1__c.field-meta.xml
<CustomField>
    <fullName>Team_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team 1</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Team_2__c.field-meta.xml
<CustomField>
    <fullName>Team_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team 2</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Team 2)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Tournament__c.field-meta.xml
<CustomField>
    <fullName>Tournament__c</fullName>
    <description>Reference to the tournament the match belongs to.</description>
    <label>Tournament</label>
    <referenceTo>Tournament__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Represents a participating team in the tournament.</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <description>Logo or emblem of the team.</description>
    <label>Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <description>Represents a specific tournament, such as the FIFA 2022 World Cup or any other tournament analyzed by Athletic Analysis.</description>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchAPI.cls
@RestResource(urlMapping='/matches/*')
global with sharing class MatchAPI {
    

    @HttpGet(urlMapping='/matches/team/*')
    global static List<Match__c> getMatchesByTeam() {
        RestRequest req = RestContext.request;
        String teamId = req.requestURI.substringBetween('/team/', '/tournament/');
        return [SELECT Id, Name, Tournament__r.Name, Team_1__r.Name, Team_2__r.Name, Team_2__r.Logo__c, Team_1__r.Logo__c, Match_Date__c
        FROM Match__c 
        WHERE (Team_1__c = :teamId OR Team_2__c = :teamId) AND (Approved__c=True) WITH SECURITY_ENFORCED];
    }
}